/**
 * @file file.h
 * @brief Utility for resolving runtime files, assets, and project paths relative to roots.
 */

#ifndef FILE_UTIL_H
#define FILE_UTIL_H

#include <string>
#include <cstdlib>
#include <fstream> // Include this header for std::ifstream
#include <coopa/debug/logger.h>
#include <root_directory.h> // This is a configuration file generated by CMake.

#include <tuple>

/**
 * @class FileUtil
 * @brief Static utility class that helps resolve correct asset, resource, and project paths.
 */
class FileUtil {
private:
    typedef std::string (*Builder) (const std::string& path); /**< Function pointer type to path builders. */
    static inline trav::debug::Logger* logger_ = new trav::debug::Logger("File"); /**< Shared static logger for file transactions. */

public:
    static inline const std::string ASSETS_PREFIX = "assets/"; /**< Standard prefix for assets folders. */
    static inline const std::string RESOURCES_PREFIX = "resources/"; /**< Standard prefix for resources folders. */

    /**
     * @brief Checks if a file path exists and is readable.
     * @param path The path to check.
     * @return True if the file exists and is openable.
     */
    static bool does_path_exist(const std::string& path) {
        std::ifstream file(path);
        return file.good();
    }

    /**
     * @brief Resolves a path relative to the root directory.
     * @param path Path tail.
     * @return Full path relative to root directory.
     */
    static std::string get_root_path(const std::string& path) {
        static std::string(*path_builder)(std::string const &) = get_root_path_builder();
        return (*path_builder)(path);
    }

    /**
     * @brief Resolves a path relative to the project directory.
     * @param path Path tail.
     * @return Full path relative to project directory.
     */
    static std::string get_project_path(const std::string& path) {
        static std::string(*proj_path_builder)(std::string const &) = get_proj_path_builder();
        return (*proj_path_builder)(path);
    }

    /**
     * @brief Resolves generic asset/resource paths dynamically by trying assets, then resources.
     * @param path Unresolved path.
     * @return A tuple of (resolved path, status boolean).
     */
    static std::tuple<std::string, bool> get_generic_asset_path(const std::string& path) {
        std::tuple<std::string, bool> asset_result = get_asset_path(path);
        if (std::get<1>(asset_result)) {
            return asset_result;
        }
        std::tuple<std::string, bool> resource_result = get_resource_path(path);
        if (std::get<1>(resource_result)) {
            return resource_result;
        }
        return std::make_tuple("", false);
    }

    /**
     * @brief Resolves a path specifically as an asset.
     * @param path Unresolved asset path.
     * @return A tuple of (resolved asset path, status boolean).
     */
    static std::tuple<std::string, bool> get_asset_path(const std::string& path) {
        size_t pos = path.find(ASSETS_PREFIX);
        std::string clean_path = (pos != std::string::npos) ? path.substr(pos + 10) : path;
        std::string asset_path = get_root_path(ASSETS_PREFIX + clean_path);
        std::string asset_path_alt = get_project_path(ASSETS_PREFIX + clean_path);
        if (does_path_exist(asset_path)) {
            return std::make_tuple(asset_path, true);
        } else if (does_path_exist(asset_path_alt)) {
            return std::make_tuple(asset_path_alt, true);
        } else {
            return std::make_tuple("", false);
        }
    }

    /**
     * @brief Resolves a path specifically as a resource.
     * @param path Unresolved resource path.
     * @return A tuple of (resolved resource path, status boolean).
     */
    static std::tuple<std::string, bool> get_resource_path(const std::string& path) {
        size_t pos = path.find(RESOURCES_PREFIX);
        std::string clean_path = (pos != std::string::npos) ? path.substr(pos + 10) : path;
        std::string resource_path = get_root_path(RESOURCES_PREFIX + clean_path);
        std::string resource_path_alt = get_project_path(RESOURCES_PREFIX + clean_path);
        if (does_path_exist(resource_path)) {
            return std::make_tuple(resource_path, true);
        } else if (does_path_exist(resource_path_alt)) {
            return std::make_tuple(resource_path_alt, true);
        } else {
            return std::make_tuple("", false);
        }
    }

    /**
     * @brief Checks if a specific asset path exists.
     * @param path The path of the asset.
     * @return True if it exists, false otherwise.
     */
    static bool does_asset_exist(const std::string& path) {
        std::tuple<std::string, bool> asset_result = get_asset_path(path);
        return std::get<1>(asset_result);
    }

    /**
     * @brief Checks if a specific resource path exists.
     * @param path The path of the resource.
     * @return True if it exists, false otherwise.
     */
    static bool does_resource_exist(const std::string& path) {
        std::tuple<std::string, bool> resource_result = get_resource_path(path);
        return std::get<1>(resource_result);
    }
     
private:
    /**
     * @brief Retrieves the project root directory from environment or fallback constants.
     * @return Reference to the root directory string.
     */
    static std::string const & get_root_dir() {
        static char const * env_root = getenv("LOGL_ROOT_PATH");
        static char const * given_root = (env_root != nullptr ? env_root : ROOT_DIR);
        static std::string root = (given_root != nullptr ? given_root : "");
        return root;
    }

    /**
     * @brief Retrieves the project source directory from environment or fallback constants.
     * @return Reference to the project directory string.
     */
    static std::string const & get_project_dir() {
        static char const * eng_proj_dir = getenv("LOGL_PROJ_PATH"); // Assuming this is the environment variable for PROJ_DIR
        static char const * given_proj_dir = (eng_proj_dir != nullptr ? eng_proj_dir : PROJ_DIR); // Assuming PROJ_DIR is defined in the CMake configuration
        static std::string proj_dir = (given_proj_dir != nullptr ? given_proj_dir : "");
        return proj_dir;
    }

    /**
     * @brief Selects the path builder for root references.
     * @return Pointer to target path resolver function.
     */
    static Builder get_root_path_builder() {
        if (get_root_dir() != "")
            return &FileUtil::get_path_relative_root;
        else
            return &FileUtil::get_path_relative_binary;
    }

    /**
     * @brief Selects the path builder for project references.
     * @return Pointer to target path resolver function.
     */
    static Builder get_proj_path_builder() {
        if (get_project_dir() != "")
            return &FileUtil::get_path_relative_project;
        else
            return &FileUtil::get_path_relative_binary; // Fallback if PROJ_DIR is not available
    }

    /**
     * @brief Concatenates paths relative to the root directory.
     */
    static std::string get_path_relative_root(const std::string& path) {
        return get_root_dir() + std::string("/") + path;
    }

    /**
     * @brief Concatenates paths relative to the project directory.
     */
    static std::string get_path_relative_project(const std::string& path) {
        return get_project_dir() + std::string("/") + path;
    }

    /**
     * @brief Formulates path relative to the build binary.
     */
    static std::string get_path_relative_binary(const std::string& path) {
        return "../../../" + path;
    }
};

#endif // FILE_UTIL_H